### ISSUE TITLE
Create an OTP Verification System 

### ISSUE THREAD

**Issue by avirajdongare** [avirajdongare/BooleanAutocrats#70]
You can easily create an application for the task of OTP verification using Python by following the steps mentioned below:

1. First, create a 6-digit random number
2. Then store the number in a variable
3. Then we need to write a program to send emails
4. When sending email, we need to use OTP as a message
5. Finally, we need to request two user inputs; first for the user’s email and then for the OTP that the user has received.

**Comment by KritikaPawan** [comment]
import os
import math
import random
import smtplib

digits="0123456789"
OTP=""
for i in range(6):
    OTP+=digits[math.floor(random.random()*10)]
otp = OTP + " is your OTP"
msg= otp
s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()
s.login("Your Gmail Account", "You app password")
emailid = input("Enter your email: ")
s.sendmail('&&&&&&&&&&&',emailid,msg)
a = input("Enter Your OTP >>: ")
if a == OTP:
    print("Verified")
else:
    print("Please Check your OTP again")
